// 函数: _Z21VertexFormatGetDefMap12VertexFormat
// 地址: 0x105e948
// 来自: E:\torrent\Cursor\Dominion_1.0.3315\split_config.arm64_v8a\lib\arm64-v8a\libTGGAndroid.so

int64_t x8_1

if (data_24b88a8 == arg1)
    x8_1 = 0
else if (data_24b88b8 == arg1)
    x8_1 = 1
else if (data_24b88c8 == arg1)
    x8_1 = 2
else if (data_24b88d8 == arg1)
    x8_1 = 3
else if (data_24b88e8 == arg1)
    x8_1 = 4
else if (data_24b88f8 == arg1)
    x8_1 = 5
else if (data_24b8908 == arg1)
    x8_1 = 6
else if (data_24b8918 == arg1)
    x8_1 = 7
else if (data_24b8928 == arg1)
    x8_1 = 8
else if (data_24b8938 == arg1)
    x8_1 = 9
else if (data_24b8948 == arg1)
    x8_1 = 0xa
else if (data_24b8958 == arg1)
    x8_1 = 0xb
else if (data_24b8968 == arg1)
    x8_1 = 0xc
else if (data_24b8978 == arg1)
    x8_1 = 0xd
else if (data_24b8988 == arg1)
    x8_1 = 0xe
else if (data_24b8998 != arg1)
    if (data_24b89a8 != arg1)
        pthread_kill(pthread_self(), 6)
        int64_t var_68 = XNoReturn()
        *macro_field_DefVertPos = 0
        *(macro_field_DefVertPos + 8) = &data_785330
        *(macro_field_DefVertPos + 0x10) = "float"
        *(macro_field_DefVertPos + 0x18) = 0
        *(macro_field_DefVertPos + 0x20) = 0
        *(macro_field_DefVertPos + 0x30) = 0
        *(macro_field_DefVertPos + 0x38) = 0
        *(macro_field_DefVertPos + 0x28) = 0
        *(macro_field_DefVertPos + 0x40) = 0
        *(macro_field_DefVertPos + 0x48) = 0
        *(macro_field_DefVertPos + 0x50) = 0
        *(macro_field_DefVertPos + 0x58) = &data_793a18
        *(macro_field_DefVertPos + 0x68) = 4
        *(macro_field_DefVertPos + 0x70) = &data_738f6a
        *(macro_field_DefVertPos + 0x78) = "float"
        *(macro_field_DefVertPos + 0x80) = 0
        *(macro_field_DefVertPos + 0x88) = 0
        *(macro_field_DefVertPos + 0x90) = 0
        *(macro_field_DefVertPos + 0x98) = 0
        *(macro_field_DefVertPos + 0xa8) = 0
        *(macro_field_DefVertPos + 0xa0) = 0
        *(macro_field_DefVertPos + 0xb0) = 0
        *(macro_field_DefVertPos + 0xb8) = 0
        *(macro_field_DefVertPos + 0xc0) = &data_793a18
        *(macro_field_DefVertPos + 0xd0) = 8
        *(macro_field_DefVertPos + 0xd8) = &data_79e3fc
        *(macro_field_DefVertPos + 0xe0) = "float"
        *(macro_field_DefVertPos + 0xe8) = 0
        *(macro_field_DefVertPos + 0xf0) = 0
        *(macro_field_DefVertPos + 0x100) = 0
        *(macro_field_DefVertPos + 0x108) = 0
        *(macro_field_DefVertPos + 0x110) = 0
        *(macro_field_DefVertPos + 0xf8) = 0
        *(macro_field_DefVertPos + 0x118) = 0
        *(macro_field_DefVertPos + 0x120) = 0
        *(macro_field_DefVertPos + 0x128) = &data_793a18
        *(macro_field_DefVertPos + 0x60) = 4
        *(macro_field_DefVertPos + 0xc8) = 4
        *(macro_field_DefVertPos + 0x130) = 4
        *macro_ptr_DefVertPos = RegisterDefMapBeforeMain(macro_map_DefVertPos)
        *macro_field_DefVertPosXY = 0
        *(macro_field_DefVertPosXY + 8) = &data_785330
        *(macro_field_DefVertPosXY + 0x10) = "float"
        *(macro_field_DefVertPosXY + 0x18) = 0
        *(macro_field_DefVertPosXY + 0x20) = 0
        *(macro_field_DefVertPosXY + 0x30) = 0
        *(macro_field_DefVertPosXY + 0x38) = 0
        *(macro_field_DefVertPosXY + 0x28) = 0
        *(macro_field_DefVertPosXY + 0x40) = 0
        *(macro_field_DefVertPosXY + 0x48) = 0
        *(macro_field_DefVertPosXY + 0x50) = 0
        *(macro_field_DefVertPosXY + 0x58) = &data_793a18
        *(macro_field_DefVertPosXY + 0x60) = 4
        *(macro_field_DefVertPosXY + 0x68) = 4
        *(macro_field_DefVertPosXY + 0x70) = &data_738f6a
        *(macro_field_DefVertPosXY + 0x78) = "float"
        *(macro_field_DefVertPosXY + 0x80) = 0
        *(macro_field_DefVertPosXY + 0x88) = 0
        *(macro_field_DefVertPosXY + 0x90) = 0
        *(macro_field_DefVertPosXY + 0x98) = 0
        *(macro_field_DefVertPosXY + 0xa8) = 0
        *(macro_field_DefVertPosXY + 0xa0) = 0
        *(macro_field_DefVertPosXY + 0xb0) = 0
        *(macro_field_DefVertPosXY + 0xb8) = 0
        *(macro_field_DefVertPosXY + 0xc0) = &data_793a18
        *(macro_field_DefVertPosXY + 0xc8) = 4
        *macro_ptr_DefVertPosXY = RegisterDefMapBeforeMain(macro_map_DefVertPosXY)
        *macro_ptr_DefVertShortPosXY = RegisterDefMapBeforeMain(macro_map_DefVertShortPosXY)
        *(macro_field_DefVertNorm + 0x68) = 4
        *macro_field_DefVertNorm = 0
        *(macro_field_DefVertNorm + 8) = &data_785330
        *(macro_field_DefVertNorm + 0x10) = "float"
        *(macro_field_DefVertNorm + 0x18) = 0
        *(macro_field_DefVertNorm + 0x20) = 0
        *(macro_field_DefVertNorm + 0x30) = 0
        *(macro_field_DefVertNorm + 0x38) = 0
        *(macro_field_DefVertNorm + 0x28) = 0
        *(macro_field_DefVertNorm + 0x40) = 0
        *(macro_field_DefVertNorm + 0x48) = 0
        *(macro_field_DefVertNorm + 0x50) = 0
        *(macro_field_DefVertNorm + 0x58) = &data_793a18
        *(macro_field_DefVertNorm + 0x60) = 4
        *(macro_field_DefVertNorm + 0x70) = &data_738f6a
        *(macro_field_DefVertNorm + 0x78) = "float"
        *(macro_field_DefVertNorm + 0x80) = 0
        *(macro_field_DefVertNorm + 0x88) = 0
        *(macro_field_DefVertNorm + 0x90) = 0
        *(macro_field_DefVertNorm + 0x98) = 0
        *(macro_field_DefVertNorm + 0xa8) = 0
        *(macro_field_DefVertNorm + 0xa0) = 0
        *(macro_field_DefVertNorm + 0xb0) = 0x3f800000
        *(macro_field_DefVertNorm + 0xb8) = 0
        *(macro_field_DefVertNorm + 0xc0) = &data_793a18
        *(macro_field_DefVertNorm + 0xc8) = 4
        *(macro_field_DefVertNorm + 0xd0) = 8
        *(macro_field_DefVertNorm + 0xd8) = &data_79e3fc
        *(macro_field_DefVertNorm + 0xe0) = "float"
        *(macro_field_DefVertNorm + 0xe8) = 0
        *(macro_field_DefVertNorm + 0xf0) = 0
        *(macro_field_DefVertNorm + 0x100) = 0
        *(macro_field_DefVertNorm + 0x108) = 0
        *(macro_field_DefVertNorm + 0x110) = 0
        *(macro_field_DefVertNorm + 0xf8) = 0
        *(macro_field_DefVertNorm + 0x118) = 0
        *(macro_field_DefVertNorm + 0x120) = 0
        *(macro_field_DefVertNorm + 0x128) = &data_793a18
        *(macro_field_DefVertNorm + 0x130) = 4
        *macro_ptr_DefVertNorm = RegisterDefMapBeforeMain(macro_map_DefVertNorm)
        *macro_field_DefVertTangent = 0
        *(macro_field_DefVertTangent + 8) = &data_785330
        *(macro_field_DefVertTangent + 0x10) = "float"
        *(macro_field_DefVertTangent + 0x18) = 0
        *(macro_field_DefVertTangent + 0x20) = 0
        *(macro_field_DefVertTangent + 0x30) = 0
        *(macro_field_DefVertTangent + 0x38) = 0
        *(macro_field_DefVertTangent + 0x28) = 0
        *(macro_field_DefVertTangent + 0x40) = 0
        *(macro_field_DefVertTangent + 0x48) = 0
        *(macro_field_DefVertTangent + 0x50) = 0
        *(macro_field_DefVertTangent + 0x58) = &data_793a18
        *(macro_field_DefVertTangent + 0x60) = 4
        *(macro_field_DefVertTangent + 0x68) = 4
        *(macro_field_DefVertTangent + 0x70) = &data_738f6a
        *(macro_field_DefVertTangent + 0x78) = "float"
        *(macro_field_DefVertTangent + 0x80) = 0
        *(macro_field_DefVertTangent + 0x88) = 0
        *(macro_field_DefVertTangent + 0x90) = 0
        *(macro_field_DefVertTangent + 0x98) = 0
        *(macro_field_DefVertTangent + 0xa8) = 0
        *(macro_field_DefVertTangent + 0xa0) = 0
        *(macro_field_DefVertTangent + 0xb0) = 0x3f800000
        *(macro_field_DefVertTangent + 0xb8) = 0
        *(macro_field_DefVertTangent + 0xc0) = &data_793a18
        *(macro_field_DefVertTangent + 0xc8) = 4
        *(macro_field_DefVertTangent + 0xd0) = 8
        *(macro_field_DefVertTangent + 0xd8) = &data_79e3fc
        *(macro_field_DefVertTangent + 0xe0) = "float"
        *(macro_field_DefVertTangent + 0xe8) = 0
        *(macro_field_DefVertTangent + 0xf0) = 0
        *(macro_field_DefVertTangent + 0x100) = 0
        *(macro_field_DefVertTangent + 0x108) = 0
        *(macro_field_DefVertTangent + 0x110) = 0
        *(macro_field_DefVertTangent + 0xf8) = 0
        *(macro_field_DefVertTangent + 0x118) = 0
        *(macro_field_DefVertTangent + 0x120) = 0
        *(macro_field_DefVertTangent + 0x128) = &data_793a18
        *(macro_field_DefVertTangent + 0x130) = 4
        *macro_ptr_DefVertTangent = RegisterDefMapBeforeMain(macro_map_DefVertTangent)
        *macro_field_DefVertBinormal = 0
        *(macro_field_DefVertBinormal + 8) = &data_785330
        *(macro_field_DefVertBinormal + 0x10) = "float"
        *(macro_field_DefVertBinormal + 0x18) = 0
        *(macro_field_DefVertBinormal + 0x20) = 0
        *(macro_field_DefVertBinormal + 0x30) = 0
        *(macro_field_DefVertBinormal + 0x38) = 0
        *(macro_field_DefVertBinormal + 0x28) = 0
        *(macro_field_DefVertBinormal + 0x40) = 0
        *(macro_field_DefVertBinormal + 0x48) = 0
        *(macro_field_DefVertBinormal + 0x50) = 0
        *(macro_field_DefVertBinormal + 0x58) = &data_793a18
        *(macro_field_DefVertBinormal + 0x60) = 4
        *(macro_field_DefVertBinormal + 0x68) = 4
        *(macro_field_DefVertBinormal + 0x70) = &data_738f6a
        *(macro_field_DefVertBinormal + 0x78) = "float"
        *(macro_field_DefVertBinormal + 0x80) = 0
        *(macro_field_DefVertBinormal + 0x88) = 0
        *(macro_field_DefVertBinormal + 0x90) = 0
        *(macro_field_DefVertBinormal + 0x98) = 0
        *(macro_field_DefVertBinormal + 0xa8) = 0
        *(macro_field_DefVertBinormal + 0xa0) = 0
        *(macro_field_DefVertBinormal + 0xb0) = 0x3f800000
        *(macro_field_DefVertBinormal + 0xb8) = 0
        *(macro_field_DefVertBinormal + 0xc0) = &data_793a18
        *(macro_field_DefVertBinormal + 0xc8) = 4
        *(macro_field_DefVertBinormal + 0xd0) = 8
        *(macro_field_DefVertBinormal + 0xd8) = &data_79e3fc
        *(macro_field_DefVertBinormal + 0xe0) = "float"
        *(macro_field_DefVertBinormal + 0xe8) = 0
        *(macro_field_DefVertBinormal + 0xf0) = 0
        *(macro_field_DefVertBinormal + 0x100) = 0
        *(macro_field_DefVertBinormal + 0x108) = 0
        *(macro_field_DefVertBinormal + 0x110) = 0
        *(macro_field_DefVertBinormal + 0xf8) = 0
        *(macro_field_DefVertBinormal + 0x118) = 0
        *(macro_field_DefVertBinormal + 0x120) = 0
        *(macro_field_DefVertBinormal + 0x128) = &data_793a18
        *(macro_field_DefVertBinormal + 0x130) = 4
        *macro_ptr_DefVertBinormal = RegisterDefMapBeforeMain(macro_map_DefVertBinormal)
        *macro_ptr_DefVertBoneIndices = RegisterDefMapBeforeMain(macro_map_DefVertBoneIndices)
        *macro_ptr_DefVertBoneWeights = RegisterDefMapBeforeMain(macro_map_DefVertBoneWeights)
        *macro_ptr_DefVertCol = RegisterDefMapBeforeMain(macro_map_DefVertCol)
        *macro_field_DefVertColF = 4
        *(macro_field_DefVertColF + 8) = &data_774ccf
        *(macro_field_DefVertColF + 0x10) = "float"
        *(macro_field_DefVertColF + 0x18) = 0
        *(macro_field_DefVertColF + 0x20) = 0
        *(macro_field_DefVertColF + 0x30) = 0
        *(macro_field_DefVertColF + 0x38) = 0
        *(macro_field_DefVertColF + 0x28) = 0
        *(macro_field_DefVertColF + 0x40) = 0
        *(macro_field_DefVertColF + 0x48) = 0
        *(macro_field_DefVertColF + 0x50) = 0
        *(macro_field_DefVertColF + 0x58) = &data_793a18
        *(macro_field_DefVertColF + 0x60) = 4
        *(macro_field_DefVertColF + 0x68) = 8
        *(macro_field_DefVertColF + 0x70) = &data_79217b
        *(macro_field_DefVertColF + 0x78) = "float"
        *(macro_field_DefVertColF + 0x80) = 0
        *(macro_field_DefVertColF + 0x88) = 0
        *(macro_field_DefVertColF + 0x90) = 0
        *(macro_field_DefVertColF + 0x98) = 0
        *(macro_field_DefVertColF + 0xa8) = 0
        *(macro_field_DefVertColF + 0xa0) = 0
        *(macro_field_DefVertColF + 0xb0) = 0
        *(macro_field_DefVertColF + 0xb8) = 0
        *(macro_field_DefVertColF + 0xc0) = &data_793a18
        *(macro_field_DefVertColF + 0xc8) = 4
        *(macro_field_DefVertColF + 0xd0) = 0xc
        *(macro_field_DefVertColF + 0xd8) = &data_7800cb
        *(macro_field_DefVertColF + 0xe0) = "float"
        *(macro_field_DefVertColF + 0xe8) = 0
        *(macro_field_DefVertColF + 0xf0) = 0
        *(macro_field_DefVertColF + 0x100) = 0
        *(macro_field_DefVertColF + 0x108) = 0
        *(macro_field_DefVertColF + 0x110) = 0
        *(macro_field_DefVertColF + 0xf8) = 0
        *(macro_field_DefVertColF + 0x118) = 0
        *(macro_field_DefVertColF + 0x120) = 0
        *(macro_field_DefVertColF + 0x128) = &data_793a18
        *(macro_field_DefVertColF + 0x130) = 4
        *(macro_field_DefVertColF + 0x138) = 0
        *(macro_field_DefVertColF + 0x140) = &data_774cd1
        *(macro_field_DefVertColF + 0x148) = "float"
        *(macro_field_DefVertColF + 0x150) = 0
        *(macro_field_DefVertColF + 0x158) = 0
        *(macro_field_DefVertColF + 0x160) = 0
        *(macro_field_DefVertColF + 0x168) = 0
        *(macro_field_DefVertColF + 0x178) = 0
        *(macro_field_DefVertColF + 0x170) = 0
        *(macro_field_DefVertColF + 0x180) = 0
        *(macro_field_DefVertColF + 0x188) = 0
        *(macro_field_DefVertColF + 0x190) = &data_793a18
        *(macro_field_DefVertColF + 0x198) = 4
        *macro_ptr_DefVertColF = RegisterDefMapBeforeMain(macro_map_DefVertColF)
        *macro_field_DefVertTex = 0
        *(macro_field_DefVertTex + 8) = &data_75d45a
        *(macro_field_DefVertTex + 0x10) = "float"
        *(macro_field_DefVertTex + 0x18) = 0
        *(macro_field_DefVertTex + 0x20) = 0
        *(macro_field_DefVertTex + 0x30) = 0
        *(macro_field_DefVertTex + 0x38) = 0
        *(macro_field_DefVertTex + 0x28) = 0
        *(macro_field_DefVertTex + 0x40) = 0
        *(macro_field_DefVertTex + 0x48) = 0
        *(macro_field_DefVertTex + 0x50) = 0
        *(macro_field_DefVertTex + 0x58) = &data_793a18
        *(macro_field_DefVertTex + 0x60) = 4
        *(macro_field_DefVertTex + 0x68) = 4
        *(macro_field_DefVertTex + 0x70) = &data_738f6c
        *(macro_field_DefVertTex + 0x78) = "float"
        *(macro_field_DefVertTex + 0x80) = 0
        *(macro_field_DefVertTex + 0x88) = 0
        *(macro_field_DefVertTex + 0x90) = 0
        *(macro_field_DefVertTex + 0x98) = 0
        *(macro_field_DefVertTex + 0xa8) = 0
        *(macro_field_DefVertTex + 0xa0) = 0
        *(macro_field_DefVertTex + 0xb0) = 0
        *(macro_field_DefVertTex + 0xb8) = 0
        *(macro_field_DefVertTex + 0xc0) = &data_793a18
        *(macro_field_DefVertTex + 0xc8) = 4
        *(macro_field_DefVertTex + 0xd0) = 8
        *(macro_field_DefVertTex + 0xd8) = &data_72d864
        *(macro_field_DefVertTex + 0xe0) = "float"
        *(macro_field_DefVertTex + 0xe8) = 0
        *(macro_field_DefVertTex + 0xf0) = 0
        *(macro_field_DefVertTex + 0x100) = 0
        *(macro_field_DefVertTex + 0x108) = 0
        *(macro_field_DefVertTex + 0x110) = 0
        *(macro_field_DefVertTex + 0xf8) = 0
        *(macro_field_DefVertTex + 0x118) = 0
        *(macro_field_DefVertTex + 0x120) = 0
        *(macro_field_DefVertTex + 0x128) = &data_793a18
        *(macro_field_DefVertTex + 0x130) = 4
        *(macro_field_DefVertTex + 0x138) = 0xc
        *(macro_field_DefVertTex + 0x140) = &data_78e9c1
        *(macro_field_DefVertTex + 0x148) = "float"
        *(macro_field_DefVertTex + 0x150) = 0
        *(macro_field_DefVertTex + 0x158) = 0
        *(macro_field_DefVertTex + 0x160) = 0
        *(macro_field_DefVertTex + 0x168) = 0
        *(macro_field_DefVertTex + 0x178) = 0
        *(macro_field_DefVertTex + 0x170) = 0
        *(macro_field_DefVertTex + 0x180) = 0
        *(macro_field_DefVertTex + 0x188) = 0
        *(macro_field_DefVertTex + 0x190) = &data_793a18
        *(macro_field_DefVertTex + 0x198) = 4
        *macro_ptr_DefVertTex = RegisterDefMapBeforeMain(macro_map_DefVertTex)
        *macro_ptr_DefVertShortTex = RegisterDefMapBeforeMain(macro_map_DefVertShortTex)
        *macro_ptr_DefVertexPosColTex = RegisterDefMapBeforeMain(macro_map_DefVertexPosColTex)
        *macro_ptr_DefVertexSprite = RegisterDefMapBeforeMain(macro_map_DefVertexSprite)
        *macro_ptr_DefVertexMutlitextureSprite =
            RegisterDefMapBeforeMain(macro_map_DefVertexMutlitextureSprite)
        *macro_ptr_DefVertexCompressedSprite =
            RegisterDefMapBeforeMain(macro_map_DefVertexCompressedSprite)
        *macro_ptr_DefVertexPosNormBinormalColTex =
            RegisterDefMapBeforeMain(macro_map_DefVertexPosNormBinormalColTex)
        *macro_ptr_DefVertexPosNormBinormalColTex2 =
            RegisterDefMapBeforeMain(macro_map_DefVertexPosNormBinormalColTex2)
        *macro_ptr_DefVertexPosNormBinormalColTexBone =
            RegisterDefMapBeforeMain(macro_map_DefVertexPosNormBinormalColTexBone)
        *macro_ptr_DefVertexPosNormColTex =
            RegisterDefMapBeforeMain(macro_map_DefVertexPosNormColTex)
        *macro_ptr_DefVertexPosNormColTex2 =
            RegisterDefMapBeforeMain(macro_map_DefVertexPosNormColTex2)
        *macro_ptr_DefVertexPosNormCol = RegisterDefMapBeforeMain(macro_map_DefVertexPosNormCol)
        *macro_ptr_DefVertexPosNormColColTex =
            RegisterDefMapBeforeMain(macro_map_DefVertexPosNormColColTex)
        *macro_ptr_DefVertexPosNormColTexBone =
            RegisterDefMapBeforeMain(macro_map_DefVertexPosNormColTexBone)
        *macro_ptr_DefVertexPosNormColTexInstance =
            RegisterDefMapBeforeMain(macro_map_DefVertexPosNormColTexInstance)
        *macro_ptr_DefVertexPosCol = RegisterDefMapBeforeMain(macro_map_DefVertexPosCol)
        *macro_ptr_DefVertexPos = RegisterDefMapBeforeMain(macro_map_DefVertexPos)
        *macro_ptr_DefVertexPosNormTex = RegisterDefMapBeforeMain(macro_map_DefVertexPosNormTex)
        *macro_ptr_DefWorldMat4 = RegisterDefMapBeforeMain(macro_map_DefWorldMat4)
        *macro_ptr_DefWVPMat4 = RegisterDefMapBeforeMain(macro_map_DefWVPMat4)
        uint64_t result = RegisterDefMapBeforeMain(macro_map_DefInstanceWorldWVP)
        *macro_ptr_DefInstanceWorldWVP = result
        data_24b88b8 = 1
        data_24b88c8 = 2
        data_24b88d8 = 3
        uint64_t x9 = *macro_ptr_DefVertexPosColTex
        uint64_t x10 = *macro_ptr_DefVertexSprite
        uint64_t x11 = *macro_ptr_DefVertexMutlitextureSprite
        data_24b88e8 = 4
        data_24b88f8 = 5
        uint64_t x12 = *macro_ptr_DefVertexCompressedSprite
        uint64_t x13 = *macro_ptr_DefVertexPosNormColTex
        uint64_t x15 = *macro_ptr_DefVertexPosNormColTex2
        uint64_t x5 = *macro_ptr_DefVertexPosNormColTexBone
        uint64_t x19 = *macro_ptr_DefVertexPosCol
        uint64_t x21 = *macro_ptr_DefVertexPos
        uint64_t x4 = *macro_ptr_DefVertexPosNormColColTex
        uint64_t x16 = *macro_ptr_DefVertexPosNormBinormalColTex
        uint64_t x17 = *macro_ptr_DefVertexPosNormBinormalColTex2
        data_24b8908 = 6
        uint64_t x1 = *macro_ptr_DefVertexPosNormBinormalColTexBone
        uint64_t x3 = *macro_ptr_DefVertexPosNormCol
        uint64_t x6 = *macro_ptr_DefVertexPosNormColTexInstance
        uint64_t x7 = *macro_ptr_DefVertexPosNormTex
        data_24b8968 = 0xc
        data_24b8918 = 8
        data_24b8928 = 7
        data_24b8998 = 0xf
        data_24b8990 = x19
        data_24b89a0 = x21
        data_24b8938 = 9
        data_24b8948 = 0xa
        data_24b8958 = 0xb
        data_24b8978 = 0xe
        data_24b88a8 = 0
        data_24b8988 = 0xd
        data_24b89a8 = 0x10
        data_24b88b0 = x9
        data_24b88c0 = x10
        data_24b88d0 = x11
        data_24b88e0 = x12
        data_24b88f0 = x13
        data_24b8900 = x15
        data_24b8910 = x16
        data_24b8920 = x17
        data_24b8930 = x1
        data_24b8940 = x3
        data_24b8950 = x4
        data_24b8960 = x5
        data_24b8970 = x6
        data_24b8980 = x7
        data_24b89b0 = result
        return result
    
    x8_1 = 0x10
else
    x8_1 = 0xf

return (&data_24b88b0)[x8_1 * 2]
