// 函数: _ZN11GameProfileC2Ev
// 地址: 0x9decec
// 来自: E:\torrent\Cursor\Dominion_1.0.3315\split_config.arm64_v8a\lib\arm64-v8a\libTGGAndroid.so

XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
void* entry_x0
__builtin_memset(entry_x0 + 0x42f8, 0, 0x20)
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
XString::XString()
*(entry_x0 + 0x5750) = zx.o(0)
DomSaveSets::DomSaveSets()
__builtin_memset(entry_x0 + 0x7580, 0, 0x20)
ClientLeaderboard::ClientLeaderboard()
__builtin_memset(entry_x0 + 0x7730, 0, 0x30)
*(entry_x0 + 0x7580) = XPooledCalloc(0x400)
*(entry_x0 + 0x7588) = 0x7f
*(entry_x0 + 0x5750) = XPooledCalloc(0x200)
*(entry_x0 + 0x5758) = 0x3f
*(entry_x0 + 0x7590) = XPooledCalloc(0x2000)
*(entry_x0 + 0x7598) = 0x3ff
*(entry_x0 + 0x7740) = XPooledCalloc(0x2000)
*(entry_x0 + 0x7748) = 0x3ff
*(entry_x0 + 0x7750) = XPooledCalloc(0x2000)
*(entry_x0 + 0x7758) = 0x3ff
*(entry_x0 + 0x7730) = XPooledCalloc(0x100)
*(entry_x0 + 0x7738) = 0x1f
*(entry_x0 + 0x42f8) = XPooledCalloc(0x2000)
*(entry_x0 + 0x4300) = 0x3ff
int64_t result = XPooledCalloc(0x2000)
*(entry_x0 + 0x4308) = result
*(entry_x0 + 0x4310) = 0x3ff
return result
