// 函数: sub_9e23e4
// 地址: 0x9e23e4
// 来自: E:\torrent\Cursor\Dominion_1.0.3315\split_config.arm64_v8a\lib\arm64-v8a\libTGGAndroid.so

*(macro_field_LocalSettings + 8) = "MusicVolume"
*(macro_field_LocalSettings + 0x10) = "float"
*(macro_field_LocalSettings + 0x70) = "SoundVolume"
*(macro_field_LocalSettings + 0x78) = "float"
*(macro_field_LocalSettings + 0x2e0) = "AppHeight"
*(macro_field_LocalSettings + 0x320) = 0x300
*(macro_field_LocalSettings + 0x3b0) = "ControlScheme"
*(macro_field_LocalSettings + 0x418) = "TextScheme"
*(macro_field_LocalSettings + 0x480) = "DeckStyle"
*(macro_field_LocalSettings + 0x48) = 0x3ecccccd
*(macro_field_LocalSettings + 0x4e8) = "Colorblind"
*(macro_field_LocalSettings + 0x548) = 0x31
*(macro_field_LocalSettings + 0x5b0) = 0x34
*(macro_field_LocalSettings + 0x550) = "ColorScheme"
*(macro_field_LocalSettings + 0x280) = "bool"
*(macro_field_LocalSettings + 0x350) = "bool"
*(macro_field_LocalSettings + 0x4f0) = "bool"
*(macro_field_LocalSettings + 0x558) = "bool"
*(macro_field_LocalSettings + 0x628) = "bool"
*(macro_field_LocalSettings + 0xb0) = 0x3f333333
*(macro_field_LocalSettings + 0x348) = "Maximized"
*(macro_field_LocalSettings + 0x620) = "VisibleLog"
*(macro_field_LocalSettings + 0x50) = 0
*(macro_field_LocalSettings + 0xb8) = 0
*(macro_field_LocalSettings + 0xd0) = 8
*(macro_field_LocalSettings + 0x210) = "Widescreen"
*(macro_field_LocalSettings + 0x278) = "Fullscreen"
*(macro_field_LocalSettings + 0x3a8) = 0x24
*(macro_field_LocalSettings + 0x478) = 0x2c
*(macro_field_LocalSettings + 0x5b8) = "Automation"
*macro_field_LocalSettings = 0
*(macro_field_LocalSettings + 0x18) = 0
*(macro_field_LocalSettings + 0x20) = 0
*(macro_field_LocalSettings + 0x30) = 0
*(macro_field_LocalSettings + 0x38) = 0
*(macro_field_LocalSettings + 0x28) = 0
*(macro_field_LocalSettings + 0x40) = 0
*(macro_field_LocalSettings + 0x58) = &data_793a18
*(macro_field_LocalSettings + 0x68) = 4
*(macro_field_LocalSettings + 0x80) = 0
*(macro_field_LocalSettings + 0x88) = 0
*(macro_field_LocalSettings + 0x90) = 0
*(macro_field_LocalSettings + 0x98) = 0
*(macro_field_LocalSettings + 0xa8) = 0
*(macro_field_LocalSettings + 0xa0) = 0
*(macro_field_LocalSettings + 0xc0) = &data_793a18
*(macro_field_LocalSettings + 0xd8) = "GameSpeed"
*(macro_field_LocalSettings + 0xe0) = &data_746c1b
*(macro_field_LocalSettings + 0xe8) = 0
*(macro_field_LocalSettings + 0xf0) = 0
*(macro_field_LocalSettings + 0x100) = 0
*(macro_field_LocalSettings + 0x108) = 0
*(macro_field_LocalSettings + 0x110) = 0
*(macro_field_LocalSettings + 0xf8) = 0
*(macro_field_LocalSettings + 0x118) = 0
*(macro_field_LocalSettings + 0x120) = 0
*(macro_field_LocalSettings + 0x128) = &data_793a18
*(macro_field_LocalSettings + 0x138) = 0xc
*(macro_field_LocalSettings + 0x140) = "GraphicsQuality"
*(macro_field_LocalSettings + 0x148) = &data_746c1b
*(macro_field_LocalSettings + 0x150) = 0
*(macro_field_LocalSettings + 0x158) = 0
*(macro_field_LocalSettings + 0x160) = 0
*(macro_field_LocalSettings + 0x168) = 0
*(macro_field_LocalSettings + 0x178) = 0
*(macro_field_LocalSettings + 0x170) = 0
*(macro_field_LocalSettings + 0x180) = 0
*(macro_field_LocalSettings + 0x188) = 0
*(macro_field_LocalSettings + 0x190) = &data_793a18
*(macro_field_LocalSettings + 0x1a0) = 0x10
*(macro_field_LocalSettings + 0x1a8) = "Language"
*(macro_field_LocalSettings + 0x1b0) = &data_746c1b
*(macro_field_LocalSettings + 0x1b8) = 0
*(macro_field_LocalSettings + 0x1c0) = 0
*(macro_field_LocalSettings + 0x1c8) = 0
*(macro_field_LocalSettings + 0x1d0) = 0
*(macro_field_LocalSettings + 0x1e0) = 0
*(macro_field_LocalSettings + 0x1d8) = 0
*(macro_field_LocalSettings + 0x1e8) = 0
*(macro_field_LocalSettings + 0x1f0) = 0
*(macro_field_LocalSettings + 0x1f8) = &data_793a18
*(macro_field_LocalSettings + 0x208) = 0x14
*(macro_field_LocalSettings + 0x218) = &data_746c1b
*(macro_field_LocalSettings + 0x220) = 0
*(macro_field_LocalSettings + 0x228) = 0
*(macro_field_LocalSettings + 0x238) = 0
*(macro_field_LocalSettings + 0x230) = 0
*(macro_field_LocalSettings + 0x248) = 0
*(macro_field_LocalSettings + 0x240) = 0
*(macro_field_LocalSettings + 0x250) = 1
*(macro_field_LocalSettings + 0x258) = 0
*(macro_field_LocalSettings + 0x260) = &data_793a18
*(macro_field_LocalSettings + 0x270) = 0x18
*(macro_field_LocalSettings + 0x288) = 0
*(macro_field_LocalSettings + 0x290) = 0
*(macro_field_LocalSettings + 0x2a0) = 0
*(macro_field_LocalSettings + 0x298) = 0
*(macro_field_LocalSettings + 0x2b0) = 0
*(macro_field_LocalSettings + 0x2a8) = 0
*(macro_field_LocalSettings + 0x2b8) = 1
*(macro_field_LocalSettings + 0x2c0) = 0
*(macro_field_LocalSettings + 0x2c8) = &data_793a18
*(macro_field_LocalSettings + 0x2d8) = 0x1c
*(macro_field_LocalSettings + 0x2e8) = &data_746c1b
*(macro_field_LocalSettings + 0x2f0) = 0
*(macro_field_LocalSettings + 0x2f8) = 0
*(macro_field_LocalSettings + 0x308) = 0
*(macro_field_LocalSettings + 0x300) = 0
*(macro_field_LocalSettings + 0x318) = 0
*(macro_field_LocalSettings + 0x310) = 0
*(macro_field_LocalSettings + 0x328) = 0
*(macro_field_LocalSettings + 0x330) = &data_793a18
*(macro_field_LocalSettings + 0x340) = 0x20
*(macro_field_LocalSettings + 0x358) = 0
*(macro_field_LocalSettings + 0x360) = 0
*(macro_field_LocalSettings + 0x370) = 0
*(macro_field_LocalSettings + 0x368) = 0
*(macro_field_LocalSettings + 0x380) = 0
*(macro_field_LocalSettings + 0x378) = 0
*(macro_field_LocalSettings + 0x390) = 0
*(macro_field_LocalSettings + 0x388) = 0
*(macro_field_LocalSettings + 0x398) = &data_793a18
*(macro_field_LocalSettings + 0x3b8) = &data_746c1b
*(macro_field_LocalSettings + 0x3c0) = 0
*(macro_field_LocalSettings + 0x3c8) = 0
*(macro_field_LocalSettings + 0x3d8) = 0
*(macro_field_LocalSettings + 0x3d0) = 0
*(macro_field_LocalSettings + 0x3e8) = 0
*(macro_field_LocalSettings + 0x3e0) = 0
*(macro_field_LocalSettings + 0x3f8) = 0
*(macro_field_LocalSettings + 0x3f0) = 0
*(macro_field_LocalSettings + 0x400) = &data_793a18
*(macro_field_LocalSettings + 0x410) = 0x28
*(macro_field_LocalSettings + 0x420) = &data_746c1b
*(macro_field_LocalSettings + 0x428) = 0
*(macro_field_LocalSettings + 0x430) = 0
*(macro_field_LocalSettings + 0x440) = 0
*(macro_field_LocalSettings + 0x438) = 0
*(macro_field_LocalSettings + 0x450) = 0
*(macro_field_LocalSettings + 0x448) = 0
*(macro_field_LocalSettings + 0x460) = 0
*(macro_field_LocalSettings + 0x458) = 0
*(macro_field_LocalSettings + 0x468) = &data_793a18
*(macro_field_LocalSettings + 0x488) = &data_746c1b
*(macro_field_LocalSettings + 0x490) = 0
*(macro_field_LocalSettings + 0x498) = 0
*(macro_field_LocalSettings + 0x4a8) = 0
*(macro_field_LocalSettings + 0x4a0) = 0
*(macro_field_LocalSettings + 0x4b8) = 0
*(macro_field_LocalSettings + 0x4b0) = 0
*(macro_field_LocalSettings + 0x4c8) = 0
*(macro_field_LocalSettings + 0x4c0) = 0
*(macro_field_LocalSettings + 0x4d0) = &data_793a18
*(macro_field_LocalSettings + 0x4e0) = 0x30
*(macro_field_LocalSettings + 0x4f8) = 0
*(macro_field_LocalSettings + 0x500) = 0
*(macro_field_LocalSettings + 0x510) = 0
*(macro_field_LocalSettings + 0x508) = 0
*(macro_field_LocalSettings + 0x520) = 0
*(macro_field_LocalSettings + 0x518) = 0
*(macro_field_LocalSettings + 0x530) = 0
*(macro_field_LocalSettings + 0x528) = 0
*(macro_field_LocalSettings + 0x538) = &data_793a18
*(macro_field_LocalSettings + 0x560) = 0
*(macro_field_LocalSettings + 0x568) = 0
*(macro_field_LocalSettings + 0x578) = 0
*(macro_field_LocalSettings + 0x570) = 0
*(macro_field_LocalSettings + 0x588) = 0
*(macro_field_LocalSettings + 0x580) = 0
*(macro_field_LocalSettings + 0x598) = 0
*(macro_field_LocalSettings + 0x590) = 0
*(macro_field_LocalSettings + 0x5a0) = &data_793a18
*(macro_field_LocalSettings + 0x5c0) = &data_746c1b
*(macro_field_LocalSettings + 0x5c8) = 0
*(macro_field_LocalSettings + 0x5d0) = 0
*(macro_field_LocalSettings + 0x5e0) = 0
*(macro_field_LocalSettings + 0x5d8) = 0
*(macro_field_LocalSettings + 0x5f0) = 0
*(macro_field_LocalSettings + 0x5e8) = 0
*(macro_field_LocalSettings + 0x600) = 0
*(macro_field_LocalSettings + 0x5f8) = 0
*(macro_field_LocalSettings + 0x608) = &data_793a18
*(macro_field_LocalSettings + 0x618) = 0x38
*(macro_field_LocalSettings + 0x630) = 0
*(macro_field_LocalSettings + 0x638) = 0
*(macro_field_LocalSettings + 0x648) = 0
*(macro_field_LocalSettings + 0x640) = 0
*(macro_field_LocalSettings + 0x658) = 0
*(macro_field_LocalSettings + 0x650) = 0
*(macro_field_LocalSettings + 0x668) = 0
*(macro_field_LocalSettings + 0x660) = 0
*(macro_field_LocalSettings + 0x670) = &data_793a18
*(macro_field_LocalSettings + 0x680) = 0x3c
*(macro_field_LocalSettings + 0x688) = "GfxTest"
*(macro_field_LocalSettings + 0x690) = &data_746c1b
*(macro_field_LocalSettings + 0x698) = 0
*(macro_field_LocalSettings + 0x6a0) = 0
*(macro_field_LocalSettings + 0x6b0) = 0
*(macro_field_LocalSettings + 0x6a8) = 0
*(macro_field_LocalSettings + 0x6c0) = 0
*(macro_field_LocalSettings + 0x6b8) = 0
*(macro_field_LocalSettings + 0x6d0) = 0
*(macro_field_LocalSettings + 0x6c8) = 0
*(macro_field_LocalSettings + 0x6d8) = &data_793a18
*(macro_field_LocalSettings + 0x60) = 4
*(macro_field_LocalSettings + 0xc8) = 4
*(macro_field_LocalSettings + 0x130) = 4
*(macro_field_LocalSettings + 0x198) = 4
*(macro_field_LocalSettings + 0x200) = 4
*(macro_field_LocalSettings + 0x268) = 4
*(macro_field_LocalSettings + 0x2d0) = 1
*(macro_field_LocalSettings + 0x338) = 4
*(macro_field_LocalSettings + 0x3a0) = 1
*(macro_field_LocalSettings + 0x408) = 4
*(macro_field_LocalSettings + 0x470) = 4
*(macro_field_LocalSettings + 0x4d8) = 4
*(macro_field_LocalSettings + 0x540) = 1
*(macro_field_LocalSettings + 0x5a8) = 1
*(macro_field_LocalSettings + 0x610) = 4
*(macro_field_LocalSettings + 0x678) = 1
*(macro_field_LocalSettings + 0x6e0) = 4
uint64_t x0_1 = RegisterDefMapBeforeMain(macro_map_LocalSettings)
*macro_ptr_LocalSettings = x0_1
*defMapLocalSettings = x0_1
uint64_t x0_3 = RegisterDefMapBeforeMain(macro_map_ChannelSettings)
*macro_ptr_ChannelSettings = x0_3
*defMapChannelSettings = x0_3
*macro_ptr_ProfileStats = RegisterDefMapBeforeMain(macro_map_ProfileStats)
*macro_ptr_ProfileEntitlment_Save = RegisterDefMapBeforeMain(macro_map_ProfileEntitlment_Save)
*macro_ptr_ProfileAchievement_Save = RegisterDefMapBeforeMain(macro_map_ProfileAchievement_Save)
*macro_ptr_EntitlementState_Save = RegisterDefMapBeforeMain(macro_map_EntitlementState_Save)
*macro_ptr_DailyGameReference_save = RegisterDefMapBeforeMain(macro_map_DailyGameReference_save)
*macro_ptr_RealtimeMatchmakingSettings =
    RegisterDefMapBeforeMain(macro_map_RealtimeMatchmakingSettings)
*macro_ptr_AsyncMatchmakingSettings = RegisterDefMapBeforeMain(macro_map_AsyncMatchmakingSettings)
*macro_ptr_SyncedDataTimestamps = RegisterDefMapBeforeMain(macro_map_SyncedDataTimestamps)
*macro_ptr_CampaignSetupMissions = RegisterDefMapBeforeMain(macro_map_CampaignSetupMissions)
*macro_ptr_SyncDataCounter = RegisterDefMapBeforeMain(macro_map_SyncDataCounter)
*macro_ptr_SyncDataEntryInt = RegisterDefMapBeforeMain(macro_map_SyncDataEntryInt)
*macro_ptr_MissionStatus = RegisterDefMapBeforeMain(macro_map_MissionStatus)
*macro_ptr_CampaignStatus = RegisterDefMapBeforeMain(macro_map_CampaignStatus)
*macro_ptr_CampaignResult = RegisterDefMapBeforeMain(macro_map_CampaignResult)
*macro_ptr_CampaignResults_Save = RegisterDefMapBeforeMain(macro_map_CampaignResults_Save)
*macro_ptr_CampaignGeneralSettings = RegisterDefMapBeforeMain(macro_map_CampaignGeneralSettings)
*macro_ptr_GameProfile_Save = RegisterDefMapBeforeMain(macro_map_GameProfile_Save)
*macro_ptr_RecommendedSetResult = RegisterDefMapBeforeMain(macro_map_RecommendedSetResult)
uint64_t x0_41 = RegisterDefMapBeforeMain(macro_map_ProfileSettings_Save)
*macro_ptr_ProfileSettings_Save = x0_41
*defMapProfileSettings = x0_41
*macro_ptr_PlayerSmartplay = RegisterDefMapBeforeMain(macro_map_PlayerSmartplay)
*macro_ptr_PlayerSmartplays_Save = RegisterDefMapBeforeMain(macro_map_PlayerSmartplays_Save)
*macro_ptr_PlayerBans_Save = RegisterDefMapBeforeMain(macro_map_PlayerBans_Save)
*macro_ptr_DomSaveSet_Save = RegisterDefMapBeforeMain(macro_map_DomSaveSet_Save)
*macro_ptr_DomSaveSets_Save = RegisterDefMapBeforeMain(macro_map_DomSaveSets_Save)
*macro_ptr_GameSet = RegisterDefMapBeforeMain(macro_map_GameSet)
*macro_ptr_PlayerConfig_Save = RegisterDefMapBeforeMain(macro_map_PlayerConfig_Save)
*macro_ptr_GameConfig_Save = RegisterDefMapBeforeMain(macro_map_GameConfig_Save)
*(macro_field_GameConfig_Net + 0x70) = &data_772956
*(macro_field_GameConfig_Net + 0x78) = "GameSet"
*(macro_field_GameConfig_Net + 8) = "seed"
*(macro_field_GameConfig_Net + 0x10) = &data_746c1b
*(macro_field_GameConfig_Net + 0x1f0) = 0
*(macro_field_GameConfig_Net + 0x270) = 0x1c
*(macro_field_GameConfig_Net + 0x390) = 0
*(macro_field_GameConfig_Net + 0x3f8) = 0
*(macro_field_GameConfig_Net + 0x68) = 4
*(macro_field_GameConfig_Net + 0xd0) = 0xc
*(macro_field_GameConfig_Net + 0x138) = 0x10
*(macro_field_GameConfig_Net + 0x1a0) = 0x14
*(macro_field_GameConfig_Net + 0x1e8) = 1
*(macro_field_GameConfig_Net + 0x208) = 0x18
*macro_field_GameConfig_Net = 0
*(macro_field_GameConfig_Net + 0x18) = 0
*(macro_field_GameConfig_Net + 0x20) = 0
*(macro_field_GameConfig_Net + 0x30) = 0
*(macro_field_GameConfig_Net + 0x38) = 0
*(macro_field_GameConfig_Net + 0x28) = 0
*(macro_field_GameConfig_Net + 0x40) = 0
*(macro_field_GameConfig_Net + 0x48) = 0
*(macro_field_GameConfig_Net + 0x50) = 0
*(macro_field_GameConfig_Net + 0x58) = &data_793a18
*(macro_field_GameConfig_Net + 0x60) = 4
*(macro_field_GameConfig_Net + 0x80) = 0
*(macro_field_GameConfig_Net + 0x88) = 0
*(macro_field_GameConfig_Net + 0x90) = 0
*(macro_field_GameConfig_Net + 0x98) = 0
*(macro_field_GameConfig_Net + 0xa8) = 0
*(macro_field_GameConfig_Net + 0xa0) = 0
*(macro_field_GameConfig_Net + 0xb0) = 0
*(macro_field_GameConfig_Net + 0xb8) = 0
*(macro_field_GameConfig_Net + 0xc0) = &data_793a18
*(macro_field_GameConfig_Net + 0xd8) = "campaign"
*(macro_field_GameConfig_Net + 0xe0) = &data_746c1b
*(macro_field_GameConfig_Net + 0xe8) = 0
*(macro_field_GameConfig_Net + 0xf0) = 0
*(macro_field_GameConfig_Net + 0x100) = 0
*(macro_field_GameConfig_Net + 0x108) = 0
*(macro_field_GameConfig_Net + 0x110) = 0
*(macro_field_GameConfig_Net + 0xf8) = 0
*(macro_field_GameConfig_Net + 0x118) = 0
*(macro_field_GameConfig_Net + 0x120) = 0
*(macro_field_GameConfig_Net + 0x128) = &data_793a18
*(macro_field_GameConfig_Net + 0x130) = 4
*(macro_field_GameConfig_Net + 0x140) = "flags"
*(macro_field_GameConfig_Net + 0x148) = &data_746c1b
*(macro_field_GameConfig_Net + 0x150) = 0
*(macro_field_GameConfig_Net + 0x158) = 0
*(macro_field_GameConfig_Net + 0x160) = 0
*(macro_field_GameConfig_Net + 0x168) = 0
*(macro_field_GameConfig_Net + 0x178) = 0
*(macro_field_GameConfig_Net + 0x170) = 0
*(macro_field_GameConfig_Net + 0x180) = 0
*(macro_field_GameConfig_Net + 0x188) = 0
*(macro_field_GameConfig_Net + 0x190) = &data_793a18
*(macro_field_GameConfig_Net + 0x198) = 4
*(macro_field_GameConfig_Net + 0x1a8) = "timecontrol"
*(macro_field_GameConfig_Net + 0x1b0) = &data_746c1b
*(macro_field_GameConfig_Net + 0x1b8) = 0
*(macro_field_GameConfig_Net + 0x1c0) = 0
*(macro_field_GameConfig_Net + 0x1c8) = 0
*(macro_field_GameConfig_Net + 0x1d0) = 0
*(macro_field_GameConfig_Net + 0x1e0) = 0
*(macro_field_GameConfig_Net + 0x1d8) = 0
*(macro_field_GameConfig_Net + 0x1f8) = &data_793a18
*(macro_field_GameConfig_Net + 0x200) = 4
*(macro_field_GameConfig_Net + 0x210) = "status"
*(macro_field_GameConfig_Net + 0x218) = &data_746c1b
*(macro_field_GameConfig_Net + 0x220) = 0
*(macro_field_GameConfig_Net + 0x228) = 0
*(macro_field_GameConfig_Net + 0x238) = 0
*(macro_field_GameConfig_Net + 0x230) = 0
*(macro_field_GameConfig_Net + 0x248) = 0
*(macro_field_GameConfig_Net + 0x240) = 0
*(macro_field_GameConfig_Net + 0x258) = 0
*(macro_field_GameConfig_Net + 0x250) = 0
*(macro_field_GameConfig_Net + 0x260) = &data_793a18
*(macro_field_GameConfig_Net + 0x268) = 4
*(macro_field_GameConfig_Net + 0x278) = "version"
*(macro_field_GameConfig_Net + 0x280) = &data_746c1b
*(macro_field_GameConfig_Net + 0x288) = 0
*(macro_field_GameConfig_Net + 0x290) = 0
*(macro_field_GameConfig_Net + 0x2a0) = 0
*(macro_field_GameConfig_Net + 0x298) = 0
*(macro_field_GameConfig_Net + 0x2b0) = 0
*(macro_field_GameConfig_Net + 0x2a8) = 0
*(macro_field_GameConfig_Net + 0x2c0) = 0
*(macro_field_GameConfig_Net + 0x2b8) = 0
*(macro_field_GameConfig_Net + 0x2c8) = &data_793a18
*(macro_field_GameConfig_Net + 0x2d0) = 4
*(macro_field_GameConfig_Net + 0x2d8) = 0x20
*(macro_field_GameConfig_Net + 0x2e0) = "setupSeed"
*(macro_field_GameConfig_Net + 0x2e8) = &data_746c1b
*(macro_field_GameConfig_Net + 0x2f0) = 0
*(macro_field_GameConfig_Net + 0x2f8) = 0
*(macro_field_GameConfig_Net + 0x308) = 0
*(macro_field_GameConfig_Net + 0x300) = 0
*(macro_field_GameConfig_Net + 0x318) = 0
*(macro_field_GameConfig_Net + 0x310) = 0
*(macro_field_GameConfig_Net + 0x328) = 0
*(macro_field_GameConfig_Net + 0x320) = 0
*(macro_field_GameConfig_Net + 0x330) = &data_793a18
*(macro_field_GameConfig_Net + 0x338) = 4
*(macro_field_GameConfig_Net + 0x340) = 0x28
*(macro_field_GameConfig_Net + 0x348) = "setupData"
*(macro_field_GameConfig_Net + 0x350) = "DefStringNetwork"
*(macro_field_GameConfig_Net + 0x358) = 0
*(macro_field_GameConfig_Net + 0x360) = 0
*(macro_field_GameConfig_Net + 0x370) = 0
*(macro_field_GameConfig_Net + 0x368) = 0
*(macro_field_GameConfig_Net + 0x380) = 0
*(macro_field_GameConfig_Net + 0x378) = 0
*(macro_field_GameConfig_Net + 0x388) = &data_793a18
*(macro_field_GameConfig_Net + 0x398) = &data_793a18
*(macro_field_GameConfig_Net + 0x3a8) = 0x30
*(macro_field_GameConfig_Net + 0x3b0) = "kingdomData"
*(macro_field_GameConfig_Net + 0x3b8) = "DefStringNetwork"
*(macro_field_GameConfig_Net + 0x3c0) = 0
*(macro_field_GameConfig_Net + 0x3c8) = 0
*(macro_field_GameConfig_Net + 0x3d8) = 0
*(macro_field_GameConfig_Net + 0x3d0) = 0
*(macro_field_GameConfig_Net + 0x3e8) = 0
*(macro_field_GameConfig_Net + 0x3e0) = 0
*(macro_field_GameConfig_Net + 0x3f0) = &data_793a18
*(macro_field_GameConfig_Net + 0x400) = &data_793a18
*(macro_field_GameConfig_Net + 0x410) = 0x38
*(macro_field_GameConfig_Net + 0x418) = "gameCode"
*(macro_field_GameConfig_Net + 0x420) = "DefStringNetwork"
*(macro_field_GameConfig_Net + 0x428) = 0
*(macro_field_GameConfig_Net + 0x430) = 0
*(macro_field_GameConfig_Net + 0x440) = 0
*(macro_field_GameConfig_Net + 0x438) = 0
*(macro_field_GameConfig_Net + 0x450) = 0
*(macro_field_GameConfig_Net + 0x448) = 0
*(macro_field_GameConfig_Net + 0x458) = &data_793a18
*(macro_field_GameConfig_Net + 0x460) = 0
*(macro_field_GameConfig_Net + 0x468) = &data_793a18
*(macro_field_GameConfig_Net + 0xc8) = 8
*(macro_field_GameConfig_Net + 0x3a0) = 8
*(macro_field_GameConfig_Net + 0x408) = 8
*(macro_field_GameConfig_Net + 0x470) = 8
*macro_ptr_GameConfig_Net = RegisterDefMapBeforeMain(macro_map_GameConfig_Net)
*macro_ptr_GameSetup_Save = RegisterDefMapBeforeMain(macro_map_GameSetup_Save)
*macro_ptr_PlayerLog = RegisterDefMapBeforeMain(macro_map_PlayerLog)
*macro_ptr_LoadingPoint = RegisterDefMapBeforeMain(macro_map_LoadingPoint)
*macro_ptr_PlayerLogs_V0 = RegisterDefMapBeforeMain(macro_map_PlayerLogs_V0)
uint64_t x0_69 = RegisterDefMapBeforeMain(macro_map_PlayerLogs_V1)
uint64_t x9 = *macro_ptr_GameSetup_Save
uint64_t x11 = *macro_ptr_PlayerLogs_V0
*macro_ptr_PlayerLogs_V1 = x0_69
*defMapGameSetup_Save = x9
*defMapPlayerLogs_V1 = x0_69
*defMapPlayerLogs_V0 = x11
*defMapPlayerLogs_Latest = x0_69
*macro_ptr_ServerBannedName = RegisterDefMapBeforeMain(macro_map_ServerBannedName)
*macro_ptr_GameCleanupSettings = RegisterDefMapBeforeMain(macro_map_GameCleanupSettings)
uint64_t result = RegisterDefMapBeforeMain(macro_map_ServerSettings)
*macro_ptr_ServerSettings = result
*defMapServerSettings = result
return result
