// 函数: sub_fd54c8
// 地址: 0xfd54c8
// 来自: E:\torrent\Cursor\Dominion_1.0.3315\split_config.arm64_v8a\lib\arm64-v8a\libTGGAndroid.so

*gHardPointBottom = strcrc32("bottom", 0)
*gHardPointCenter = strcrc32("center", 0)
*gHardPointTop = strcrc32("top", 0)
*macro_ptr_DefAttachObject = RegisterDefMapBeforeMain(macro_map_DefAttachObject)
*macro_ptr_DefStructureAttachment = RegisterDefMapBeforeMain(macro_map_DefStructureAttachment)
*macro_ptr_DefSubMesh = RegisterDefMapBeforeMain(macro_map_DefSubMesh)
*macro_ptr_DefStructureBone = RegisterDefMapBeforeMain(macro_map_DefStructureBone)
*macro_ptr_DefHardPoint = RegisterDefMapBeforeMain(macro_map_DefHardPoint)
uint64_t x0_14 = RegisterDefMapBeforeMain(macro_map_DefHitBox)
*macro_field_DefStructureImportData = 8
*(macro_field_DefStructureImportData + 0x1a8) = "meshBounds"
*(macro_field_DefStructureImportData + 0x1b0) = "BBox"
*(macro_field_DefStructureImportData + 0x210) = "height"
*(macro_field_DefStructureImportData + 0x270) = 0x5c
*(macro_field_DefStructureImportData + 0x278) = "radius"
*(macro_field_DefStructureImportData + 0x2d8) = 0x68
*(macro_field_DefStructureImportData + 0x60) = 0x15000000008
*(macro_field_DefStructureImportData + 0x2e0) = "pAnimClips"
*(macro_field_DefStructureImportData + 0x2f8) = 0x60
*macro_ptr_DefHitBox = x0_14
*(macro_field_DefStructureImportData + 0x300) = "DefAnimationClip"
*(macro_field_DefStructureImportData + 0xc8) = 0xd800000008
*(macro_field_DefStructureImportData + 0x130) = 0x4000000008
*(macro_field_DefStructureImportData + 0x198) = 0x4800000008
*(macro_field_DefStructureImportData + 8) = "pSubMeshArray"
*(macro_field_DefStructureImportData + 0x10) = "variablearray"
*(macro_field_DefStructureImportData + 0x18) = 0
*(macro_field_DefStructureImportData + 0x20) = 0
*(macro_field_DefStructureImportData + 0x30) = 0
*(macro_field_DefStructureImportData + 0x38) = 0
*(macro_field_DefStructureImportData + 0x28) = "DefSubMesh"
*(macro_field_DefStructureImportData + 0x40) = 0
*(macro_field_DefStructureImportData + 0x48) = 0
*(macro_field_DefStructureImportData + 0x50) = 0
*(macro_field_DefStructureImportData + 0x58) = &data_793a18
*(macro_field_DefStructureImportData + 0x68) = 0x18
*(macro_field_DefStructureImportData + 0x70) = "pBoneArray"
*(macro_field_DefStructureImportData + 0x78) = "variablearray"
*(macro_field_DefStructureImportData + 0x80) = 0
*(macro_field_DefStructureImportData + 0x88) = 0x10
*(macro_field_DefStructureImportData + 0x98) = 0
*(macro_field_DefStructureImportData + 0xa0) = 0
*(macro_field_DefStructureImportData + 0x90) = "DefStructureBone"
*(macro_field_DefStructureImportData + 0xa8) = 0
*(macro_field_DefStructureImportData + 0xb0) = 0
*(macro_field_DefStructureImportData + 0xb8) = 0
*(macro_field_DefStructureImportData + 0xc0) = &data_793a18
*(macro_field_DefStructureImportData + 0xd0) = 0x28
*(macro_field_DefStructureImportData + 0xd8) = "pHardPointArray"
*(macro_field_DefStructureImportData + 0xe0) = "variablearray"
*(macro_field_DefStructureImportData + 0xe8) = 0
*(macro_field_DefStructureImportData + 0xf0) = 0x20
*(macro_field_DefStructureImportData + 0x110) = 0
*(macro_field_DefStructureImportData + 0xf8) = "DefHardPoint"
*(macro_field_DefStructureImportData + 0x100) = 0
*(macro_field_DefStructureImportData + 0x108) = 0
*(macro_field_DefStructureImportData + 0x118) = 0
*(macro_field_DefStructureImportData + 0x120) = 0
*(macro_field_DefStructureImportData + 0x128) = &data_793a18
*(macro_field_DefStructureImportData + 0x138) = 0x38
*(macro_field_DefStructureImportData + 0x140) = "pHitBoxArray"
*(macro_field_DefStructureImportData + 0x148) = "variablearray"
*(macro_field_DefStructureImportData + 0x150) = 0
*(macro_field_DefStructureImportData + 0x158) = 0x30
*(macro_field_DefStructureImportData + 0x168) = 0
*(macro_field_DefStructureImportData + 0x170) = 0
*(macro_field_DefStructureImportData + 0x160) = "DefHitBox"
*(macro_field_DefStructureImportData + 0x178) = 0
*(macro_field_DefStructureImportData + 0x180) = 0
*(macro_field_DefStructureImportData + 0x188) = 0
*(macro_field_DefStructureImportData + 0x190) = &data_793a18
*(macro_field_DefStructureImportData + 0x1a0) = 0x40
*(macro_field_DefStructureImportData + 0x1b8) = 0
*(macro_field_DefStructureImportData + 0x1c0) = 0
*(macro_field_DefStructureImportData + 0x1c8) = 0
*(macro_field_DefStructureImportData + 0x1d0) = 0
*(macro_field_DefStructureImportData + 0x1e0) = 0
*(macro_field_DefStructureImportData + 0x1d8) = 0
*(macro_field_DefStructureImportData + 0x1e8) = 0
*(macro_field_DefStructureImportData + 0x1f0) = 0
*(macro_field_DefStructureImportData + 0x1f8) = &data_793a18
*(macro_field_DefStructureImportData + 0x208) = 0x58
*(macro_field_DefStructureImportData + 0x218) = "float"
*(macro_field_DefStructureImportData + 0x220) = 0
*(macro_field_DefStructureImportData + 0x228) = 0
*(macro_field_DefStructureImportData + 0x238) = 0
*(macro_field_DefStructureImportData + 0x230) = 0
*(macro_field_DefStructureImportData + 0x248) = 0
*(macro_field_DefStructureImportData + 0x240) = 0
*(macro_field_DefStructureImportData + 0x258) = 0
*(macro_field_DefStructureImportData + 0x250) = 0
*(macro_field_DefStructureImportData + 0x260) = &data_793a18
*(macro_field_DefStructureImportData + 0x280) = "float"
*(macro_field_DefStructureImportData + 0x288) = 0
*(macro_field_DefStructureImportData + 0x290) = 0
*(macro_field_DefStructureImportData + 0x2a0) = 0
*(macro_field_DefStructureImportData + 0x298) = 0
*(macro_field_DefStructureImportData + 0x2b0) = 0
*(macro_field_DefStructureImportData + 0x2a8) = 0
*(macro_field_DefStructureImportData + 0x2c0) = 0
*(macro_field_DefStructureImportData + 0x2b8) = 0
*(macro_field_DefStructureImportData + 0x2c8) = &data_793a18
*(macro_field_DefStructureImportData + 0x2e8) = "variablearray"
*(macro_field_DefStructureImportData + 0x2f0) = 0
*(macro_field_DefStructureImportData + 0x310) = 0
*(macro_field_DefStructureImportData + 0x308) = 0
*(macro_field_DefStructureImportData + 0x318) = 0
*(macro_field_DefStructureImportData + 0x328) = 0
*(macro_field_DefStructureImportData + 0x320) = 0
*(macro_field_DefStructureImportData + 0x200) = 0x18
*(macro_field_DefStructureImportData + 0x330) = &data_793a18
*(macro_field_DefStructureImportData + 0x268) = 4
*(macro_field_DefStructureImportData + 0x2d0) = 4
*(macro_field_DefStructureImportData + 0x338) = 0x1800000008
*macro_ptr_DefStructureImportData = RegisterDefMapBeforeMain(macro_map_DefStructureImportData)
*macro_ptr_DefSubMeshState = RegisterDefMapBeforeMain(macro_map_DefSubMeshState)
*macro_ptr_DefStructureMaterial = RegisterDefMapBeforeMain(macro_map_DefStructureMaterial)
*macro_ptr_DefStructureMaterialTable = RegisterDefMapBeforeMain(macro_map_DefStructureMaterialTable)
*macro_ptr_DefLook = RegisterDefMapBeforeMain(macro_map_DefLook)
*(macro_field_DefStructure + 8) = "pStructureImportData"
*(macro_field_DefStructure + 0x10) = "subdefptr"
*(macro_field_DefStructure + 0x120) = 0
*(macro_field_DefStructure + 0x1f0) = 0
*(macro_field_DefStructure + 0x68) = 0x18
*(macro_field_DefStructure + 0x88) = 0x10
*(macro_field_DefStructure + 0x200) = 4
*(macro_field_DefStructure + 0x268) = 4
*(macro_field_DefStructure + 0xd0) = 0x20
*(macro_field_DefStructure + 0xd8) = "assetAnimDefault"
*(macro_field_DefStructure + 0xe0) = "DefAssetPtr"
*(macro_field_DefStructure + 0x110) = 0xa
*(macro_field_DefStructure + 0x138) = 0x30
*(macro_field_DefStructure + 0x1e8) = 0x3f800000
*(macro_field_DefStructure + 0x60) = 0x7000000008
*(macro_field_DefStructure + 0xc8) = 0xe000000008
*(macro_field_DefStructure + 0x1a8) = "scale"
*(macro_field_DefStructure + 0x1b0) = "float"
*(macro_field_DefStructure + 0x210) = "filterGroup"
*(macro_field_DefStructure + 0x218) = &data_746c1b
*(macro_field_DefStructure + 0x208) = 0x3c
*(macro_field_DefStructure + 0x158) = 0x28
*(macro_field_DefStructure + 0x1a0) = 0x38
*macro_field_DefStructure = 0
*(macro_field_DefStructure + 0x18) = 0
*(macro_field_DefStructure + 0x20) = 0
*(macro_field_DefStructure + 0x48) = 0
*(macro_field_DefStructure + 0x30) = 0
*(macro_field_DefStructure + 0x38) = 0
*(macro_field_DefStructure + 0x28) = "DefStructureImportData"
*(macro_field_DefStructure + 0x40) = 0
*(macro_field_DefStructure + 0x58) = &data_793a18
*(macro_field_DefStructure + 0x70) = "pSubMeshStateArray"
*(macro_field_DefStructure + 0x78) = "variablearray"
*(macro_field_DefStructure + 0x80) = 0
*(macro_field_DefStructure + 0x98) = 0
*(macro_field_DefStructure + 0xa0) = 0
*(macro_field_DefStructure + 0x90) = "DefSubMeshState"
*(macro_field_DefStructure + 0xa8) = 0
*(macro_field_DefStructure + 0xb0) = 0
*(macro_field_DefStructure + 0xb8) = 0
*(macro_field_DefStructure + 0xc0) = &data_793a18
*(macro_field_DefStructure + 0xe8) = 0
*(macro_field_DefStructure + 0xf0) = 0
*(macro_field_DefStructure + 0x100) = 0
*(macro_field_DefStructure + 0x108) = 0
*(macro_field_DefStructure + 0xf8) = 0
*(macro_field_DefStructure + 0x118) = &data_793a18
*(macro_field_DefStructure + 0x128) = &data_793a18
*(macro_field_DefStructure + 0x140) = "pAttachments"
*(macro_field_DefStructure + 0x148) = "variablearray"
*(macro_field_DefStructure + 0x150) = 0
*(macro_field_DefStructure + 0x168) = 0
*(macro_field_DefStructure + 0x170) = 0
*(macro_field_DefStructure + 0x160) = "DefStructureAttachment"
*(macro_field_DefStructure + 0x178) = 0
*(macro_field_DefStructure + 0x180) = 0
*(macro_field_DefStructure + 0x188) = 0
*(macro_field_DefStructure + 0x190) = &data_793a18
*(macro_field_DefStructure + 0x198) = 0x1800000008
*(macro_field_DefStructure + 0x1b8) = 0
*(macro_field_DefStructure + 0x1c0) = 0
*(macro_field_DefStructure + 0x1c8) = 0
*(macro_field_DefStructure + 0x1d0) = 0
*(macro_field_DefStructure + 0x1e0) = 0
*(macro_field_DefStructure + 0x1d8) = 0
*(macro_field_DefStructure + 0x1f8) = &data_793a18
*(macro_field_DefStructure + 0x220) = 0
*(macro_field_DefStructure + 0x228) = 0
*(macro_field_DefStructure + 0x238) = 0
*(macro_field_DefStructure + 0x230) = 0
*(macro_field_DefStructure + 0x240) = gpObjectFilterGroupSymbolMap
*(macro_field_DefStructure + 0x248) = 0
*(macro_field_DefStructure + 0x250) = 0
*(macro_field_DefStructure + 0x260) = &data_793a18
*(macro_field_DefStructure + 0x270) = 0x40
*(macro_field_DefStructure + 0x278) = "materialTable"
*(macro_field_DefStructure + 0x280) = "DefStructureMaterialTable"
*(macro_field_DefStructure + 0x288) = 0
*(macro_field_DefStructure + 0x290) = 0
*(macro_field_DefStructure + 0x2a0) = 0
*(macro_field_DefStructure + 0x298) = 0
*(macro_field_DefStructure + 0x2b0) = 0
*(macro_field_DefStructure + 0x2a8) = 0
*(macro_field_DefStructure + 0x2c0) = 0
*(macro_field_DefStructure + 0x2b8) = 0
*(macro_field_DefStructure + 0x2c8) = &data_793a18
*(macro_field_DefStructure + 0x2d8) = 0x50
*(macro_field_DefStructure + 0x2e0) = "looks"
*(macro_field_DefStructure + 0x2e8) = "variablearray"
*(macro_field_DefStructure + 0x2f0) = 0
*(macro_field_DefStructure + 0x2f8) = 0x58
*(macro_field_DefStructure + 0x300) = "DefLook"
*(macro_field_DefStructure + 0x310) = 0
*(macro_field_DefStructure + 0x308) = 0
*(macro_field_DefStructure + 0x318) = 0
*(macro_field_DefStructure + 0x328) = 0
*(macro_field_DefStructure + 0x320) = 0
*(macro_field_DefStructure + 0x330) = &data_793a18
*(macro_field_DefStructure + 0x50) = 8
*(macro_field_DefStructure + 0x130) = 8
*(macro_field_DefStructure + 0x258) = 2
*(macro_field_DefStructure + 0x2d0) = 0x10
*(macro_field_DefStructure + 0x338) = 0x1800000008
uint64_t result = RegisterDefMapBeforeMain(macro_map_DefStructure)
*macro_ptr_DefStructure = result
return result
